### ISSUE TITLE
NullPointerException when a fox/polar bear dies from non-entity damage source

### ISSUE THREAD

**Issue by SilverDavidMC** [lilypuree/WanderingTrapper#2]
The title basically says it all. If a fox or polar bear dies from damage not caused by an entity, like lava or suffocation, the game crashes. 

It's happening in your ModSetup class on lines 110, 118, and 126 since `entity.getSource().getTrueSource()` is returning null for those types of damage sources.

**Comment by lilypuree** [comment]
Thanks for catching the bug!
