### ISSUE TITLE
Villagers don't seem to become furriers?

### ISSUE THREAD

**Issue by Derpford** [lilypuree/WanderingTrapper#6]
For some reason, villagers seem reluctant to become furriers. I've yet to find a naturally-spawning furrier job post, and when I craft one, no matter where I place it, villagers just don't bother becoming furriers. Am I doing something wrong?

Edit: This is on Fabric 1.18.1.

**Comment by Derpford** [comment]
I see a green sparkle when a villager walks near the pelt scraper, but they don't become a furrier.

**Comment by Derpford** [comment]
I was finally able to summon a Furrier by using a command that set the Furrier's job site block manually. Summoning a villager with their jobsite set to a pelt log, but no profession, left them as a regular villager.

So it looks like there's nothing in place to actually make villagers into furriers. They don't set their job sites or change their profession. In addition, there doesn't appear to be a language entry for the furrier.

**Comment by lilypuree** [comment]
Fixed
