### ISSUE TITLE
[Suggestion] Nerf wandering trapper projectiles towards players, or reduce armor damage

### ISSUE THREAD

**Issue by orlouge** [lilypuree/WanderingTrapper#9]
Currently, the trapper can easily destroy high-tier armors if a player happens to be in the trajectory between the trapper and the mob being targeted, or if the player angered the trapper. Being killed in one shot may make sense, but the huge damage done to armors seems a bit excessive for just a single bullet.

**Comment by lilypuree** [comment]
Resolved by 0bc04beaa938de59bc0a14224269d21fe42419ed
